language: R
r:
  - release
sudo: false
cache: packages
warnings_are_errors: false
os:
  - osx
after_failure:
  - cat /home/travis/build/hazimehh/L0Learn/L0Learn.Rcheck/00check.log
after_success:
  - cat /home/travis/build/hazimehh/L0Learn/L0Learn.Rcheck/00check.log
  - travis_wait 300 Rscript -e "covr::codecov(quiet = FALSE, token='6f2e6703-ee4f-4479-b079-1d5d219786f4')"
