os:
  - osx
language: R
r:
  - release
sudo: false
cache: packages
warnings_are_errors: false
after_failure:
  - cat /home/travis/build/hazimehh/L0Learn/L0Learn.Rcheck/00check.log
after_success:
  - cat /home/travis/build/hazimehh/L0Learn/L0Learn.Rcheck/00check.log
